---

apiVersion: v1
kind: Service
metadata:
  name: one-click-hello
spec:
  selector:
    app: one-click-hello
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-click-hello
spec:
  selector:
    matchLabels:
      app: one-click-hello
  replicas: 1
  template:
    metadata:
      labels:
        app: one-click-hello
    spec:
      containers:
      - name: one-click-hello
        image: rg.nl-ams.scw.cloud/image-brk-soft/henyxia/breakathon-soft-chall1:$GITHUB_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 80
